# Generated by Django 5.2.13 on 2026-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='dias_atencion',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='negocio',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='negocio',
            name='ruc',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='categoria',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('tienda', 'Tienda'), ('farmacia', 'Farmacia'), ('bodega', 'Bodega'), ('mercado', 'Mercado'), ('postres', 'Postres'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
    ]
