# Generated by Django 5.2.13 on 2026-05-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20260516_2354'),
        ('security', '0004_hu08_seguimiento'),
    ]

    operations = [
    ]
