# Generated by Django 5.2.13 on 2026-05-24 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_merge_0003_auto_20260516_2354_0004_hu08_seguimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='lat_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='lng_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]