# Generated by Django 5.2.13 on 2026-06-20 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_remove_pedido_lat_entrega_remove_pedido_lng_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('bebida', 'Bebida'), ('postre', 'Postre'), ('snack', 'Snack'), ('medicina', 'Medicina'), ('higiene', 'Higiene'), ('abarrotes', 'Abarrotes'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='HistorialCambioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('creacion', 'Creación'), ('precio', 'Modificación de precio'), ('disponible', 'Cambio de disponibilidad'), ('nombre', 'Cambio de nombre'), ('descripcion', 'Cambio de descripción'), ('categoria', 'Cambio de categoría'), ('eliminacion', 'Eliminación')], max_length=20)),
                ('valor_anterior', models.CharField(blank=True, default='', max_length=255)),
                ('valor_nuevo', models.CharField(blank=True, default='', max_length=255)),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='security.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_producto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_cambio_producto',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilRepartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8)),
                ('vehiculo', models.CharField(choices=[('moto', 'Moto'), ('bicicleta', 'Bicicleta'), ('a_pie', 'A pie'), ('auto', 'Auto')], default='moto', max_length=20)),
                ('zona_cobertura', models.CharField(blank=True, max_length=255)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_repartidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_repartidor',
            },
        ),
        migrations.DeleteModel(
            name='HistorialEstadoPedido',
        ),
    ]
