# Generated by Django 5.2.13 on 2026-06-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_producto_categoria_producto_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='zona',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
