# Generated by Django 5.2.13 on 2026-06-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_producto_categoria_producto_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(blank=True, max_length=15)),
                ('dni', models.CharField(blank=True, max_length=8)),
                ('vehiculo', models.CharField(choices=[('moto', 'Moto'), ('bicicleta', 'Bicicleta'), ('a_pie', 'A pie'), ('auto', 'Auto')], default='moto', max_length=20)),
                ('zona_cobertura', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'repartidor',
            },
        ),
    ]
