# Generated by Django 5.2.13 on 2026-06-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_usuario_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='zona',
        ),
    ]
