# Generated by Django 5.2.13 on 2026-06-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_add_repartidor_table'),
        ('security', '0010_crear_perfil_repartidor'),
    ]

    operations = [
    ]
