# Generated by Django 5.2.13 on 2026-06-23 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_merge_20260623_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('yape', 'Yape'), ('plin', 'Plin')], default='tarjeta', max_length=20)),
                ('numero_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='security.pedido')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        # migrations.DeleteModel(
          #   name='Repartidor',
        # ),
    ]
