# Generated by Django 5.2.13 on 2026-07-07 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_crear_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='security.pedido')),
            ],
            options={
                'db_table': 'calificacion',
            },
        ),
        migrations.AlterField(
            model_name='perfilrepartidor',
            name='dni',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
