# Generated by Django 5.2.13 on 2026-07-07 17:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_calificacion_y_campos_obligatorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='pago',
            name='comision_plataforma',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_comercio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_repartidor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
