# Generated by Django 5.2.13 on 2026-07-07 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_hu14_hu15_distribucion_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido_no_llego', 'El pedido no llegó'), ('pedido_incompleto', 'Pedido incompleto'), ('producto_danado', 'Producto dañado'), ('repartidor_problema', 'Problema con el repartidor'), ('cobro_incorrecto', 'Cobro incorrecto'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='abierto', max_length=20)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='security.pedido')),
            ],
            options={
                'db_table': 'incidencia',
                'ordering': ['-created_at'],
            },
        ),
    ]
