# Generated by Django 5.2.13 on 2026-07-10 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio_id', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('comida', 'Comida'), ('bebida', 'Bebida'), ('postre', 'Postre'), ('snack', 'Snack'), ('medicina', 'Medicina'), ('higiene', 'Higiene'), ('abarrotes', 'Abarrotes'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='HistorialCambioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.BigIntegerField(blank=True, null=True)),
                ('tipo_cambio', models.CharField(choices=[('creacion', 'Creacion'), ('precio', 'Precio'), ('disponible', 'Disponible'), ('nombre', 'Nombre'), ('descripcion', 'Descripcion'), ('categoria', 'Categoria'), ('eliminacion', 'Eliminacion')], max_length=20)),
                ('valor_anterior', models.CharField(blank=True, default='', max_length=255)),
                ('valor_nuevo', models.CharField(blank=True, default='', max_length=255)),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='productos.producto')),
            ],
            options={
                'db_table': 'historial_cambio_producto',
                'ordering': ['-fecha'],
            },
        ),
    ]
