apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: llegaya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: llegaya/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRO_SERVICIOS_URL
              value: http://registro-servicios:8500
            - name: CORS_ALLOWED_ORIGINS
              value: "https://llega-ya-fronted-eosin.vercel.app,http://localhost:4200"
          readinessProbe:
            httpGet:
              path: /salud
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /salud
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
