from django.urls import path

from .views import (
    AsignarRepartidorView,
    CalificacionPedidoView,
    CalificarPedidoView,
    CancelarPedidoView,
    CompletarPedidoView,
    CrearIncidenciaView,
    CrearPedidoView,
    DetallePedidoConPagoView,
    DetallePedidoView,
    HistorialPagosView,
    IncidenciasListView,
    ListaMisPedidosView,
    PagarPedidoView,
    PedidosDisponiblesView,
    PrediccionDemandaView,
    PromedioCalificacionesRepartidorView,
    ReporteDiarioView,
    ReporteNegocioDatosView,
    ResponderIncidenciaView,
)

urlpatterns = [
    path("crear/", CrearPedidoView.as_view(), name="pedidos-crear"),
    path("mis-pedidos/", ListaMisPedidosView.as_view(), name="pedidos-mis-pedidos"),
    path("disponibles/", PedidosDisponiblesView.as_view(), name="pedidos-disponibles"),
    # Rutas de coleccion (sin <pk>) primero, para que no las capture "<int:pk>/"
    path("pagos/", HistorialPagosView.as_view(), name="pedidos-pagos-historial"),
    path("calificaciones/promedio/", PromedioCalificacionesRepartidorView.as_view(), name="pedidos-calificaciones-promedio"),
    path("incidencias/", IncidenciasListView.as_view(), name="pedidos-incidencias-lista"),
    path("incidencias/<int:pk>/responder/", ResponderIncidenciaView.as_view(), name="pedidos-incidencias-responder"),
    path("reportes/diario/", ReporteDiarioView.as_view(), name="pedidos-reporte-diario"),
    path("reportes/negocio/", ReporteNegocioDatosView.as_view(), name="pedidos-reporte-negocio"),
    path("predicciones/demanda/", PrediccionDemandaView.as_view(), name="pedidos-prediccion-demanda"),
    path("<int:pk>/", DetallePedidoView.as_view(), name="pedidos-detalle"),
    path("<int:pk>/detalle/", DetallePedidoConPagoView.as_view(), name="pedidos-detalle-con-pago"),
    path("<int:pk>/cancelar/", CancelarPedidoView.as_view(), name="pedidos-cancelar"),
    path("<int:pk>/completar/", CompletarPedidoView.as_view(), name="pedidos-completar"),
    path("<int:pk>/asignar-repartidor/", AsignarRepartidorView.as_view(), name="pedidos-asignar-repartidor"),
    path("<int:pk>/pagar/", PagarPedidoView.as_view(), name="pedidos-pagar"),
    path("<int:pk>/calificar/", CalificarPedidoView.as_view(), name="pedidos-calificar"),
    path("<int:pk>/calificacion/", CalificacionPedidoView.as_view(), name="pedidos-calificacion"),
    path("<int:pk>/incidencias/", CrearIncidenciaView.as_view(), name="pedidos-incidencias-crear"),
]
