# Generated by Django 5.2.13 on 2026-07-10 02:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario_id', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('restaurante', 'Restaurante'), ('tienda', 'Tienda'), ('farmacia', 'Farmacia'), ('bodega', 'Bodega'), ('mercado', 'Mercado'), ('postres', 'Postres'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruc', models.CharField(blank=True, max_length=11)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=9)),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('dias_atencion', models.JSONField(blank=True, default=list)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
            ],
            options={
                'db_table': 'negocio',
            },
        ),
    ]
