apiVersion: v1
kind: ConfigMap
metadata:
  name: servicio-repartidores-config
  namespace: llegaya
data:
  NOMBRE_SERVICIO: servicio-repartidores
  DJANGO_PERFIL: k8s
  REGISTRO_SERVICIOS_URL: http://registro-servicios:8500
  CONFIG_SERVER_URL: http://config-server:8600
  API_GATEWAY_URL: http://api-gateway:8080
  SERVICIO_HOST: servicio-repartidores
  SERVICIO_PUERTO: "8005"
  DEBUG: "false"
  CORS_ALLOWED_ORIGINS: "https://CAMBIAR-frontend.vercel.app"
