# Generated by Django 5.2.13 on 2026-07-14 15:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repartidor_id', models.BigIntegerField()),
                ('estrellas', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'calificacion',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.BigIntegerField()),
                ('tipo', models.CharField(choices=[('pedido_no_llego', 'El pedido no llego'), ('pedido_incompleto', 'Pedido incompleto'), ('producto_danado', 'Producto danado'), ('repartidor_problema', 'Problema con el repartidor'), ('cobro_incorrecto', 'Cobro incorrecto'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='abierto', max_length=20)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'incidencia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta de credito/debito'), ('yape', 'Yape'), ('plin', 'Plin')], default='tarjeta', max_length=20)),
                ('numero_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comision_plataforma', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_comercio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_repartidor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
    ]
