apiVersion: v1
kind: Service
metadata:
  name: registro-servicios
  namespace: llegaya
spec:
  type: ClusterIP
  selector:
    app: registro-servicios
  ports:
    - port: 8500
      targetPort: 8500
