apiVersion: v1
kind: Service
metadata:
  name: servicio-productos
  namespace: llegaya
spec:
  type: ClusterIP
  selector:
    app: servicio-productos
  ports:
    - port: 8003
      targetPort: 8003
