apiVersion: v1
kind: ConfigMap
metadata:
  name: servicio-negocios-config
  namespace: llegaya
data:
  NOMBRE_SERVICIO: servicio-negocios
  DJANGO_PERFIL: k8s
  REGISTRO_SERVICIOS_URL: http://registro-servicios:8500
  CONFIG_SERVER_URL: http://config-server:8600
  SERVICIO_HOST: servicio-negocios
  SERVICIO_PUERTO: "8002"
  DEBUG: "false"
  CORS_ALLOWED_ORIGINS: "https://llega-ya-fronted-eosin.vercel.app"
